In [1]:
import numpy as np
import pandas as pd
from sklearn import  datasets #for the loading iris dataset
from sklearn.model_selection import train_test_split #for the splitting data
from sklearn.neighbors import KNeighborsClassifier #for the implementing 
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
import random

In [2]:
#for loading data
iris = datasets.load_iris()
x = iris.data    #iris features
y = iris.target  #iris types

In [3]:
x.shape  #iris data set has 4 features and 15 rows

(150, 4)

In [4]:
y.shape

(150,)

In [5]:
iris.feature_names #features names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [6]:
iris.target_names #iris types names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [7]:
print(x) #print features

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [8]:
print(y) #print target
# 0 for the 'setosa', 1 for the 'versicolor', 2 for the 'virginica'

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [9]:
dfX = pd.DataFrame(x, columns = iris['feature_names'])
dfY = pd.DataFrame(y, columns = ["types"])
print("DATAS\n",dfX.head())
print("TARGETS\n",dfY.head())

DATAS
    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2
TARGETS
    types
0      0
1      0
2      0
3      0
4      0


In [10]:
#split the data into x_train, x_test, y_train, y_test
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.30,random_state=0)

In [11]:
print("Shape of the x_train:",x_train.shape) 
print("Shape of the y_train:",y_train.shape)
print("Shape of the x_test:", x_test.shape)
print("Shape of the y_test:", y_test.shape)

Shape of the x_train: (105, 4)
Shape of the y_train: (105,)
Shape of the x_test: (45, 4)
Shape of the y_test: (45,)


In [12]:
class KNN():
    
    #k shows how many nearest neighbors to look and predict
    def __init__(self,x_train,y_train, k):
        self.k = k                          # k is an integer                  
        self.x_train = x_train              # we get this as an array
        self.y_train = y_train              # we get this as an array
    
    
    #The predict function takes rows from x_test, predicts and returns y_pred.
    def predict(self,x_test):
        y_pred=[]  #a prediction array
        for test_row in x_test: #test_row is a row in the x_test
            y_pred.append(self.prediction(test_row))
        return y_pred    
    
    #It takes the sorted distances with the sort_distance function and 
    #takes the first k distances out of them. With the function count, 
    #a selection is made among the first k neighbors.
    def prediction(self, test_row):
        distances = self.sort_distances(test_row)
        neighbors = [] #an array for the first k neighbors
        for i in range(self.k):   #The first k neighbors are taken from the sorted array list.
            neighbors.append(distances[i][0]) 
        
        pred = self.count(neighbors) #The result of the count function is returned.
        return pred
    
    #formula in euclidean calculation
    #sqrt((test_row[0]-train[0])**2 + (test_row[1]-train[1])**2 + (test_row[2]-train[2])**2 +(test_row[3]-train[3])**2)
    #we have 4 features in iris dataset
    def euclidean(self, test_row, train_row): 
        distance = 0.0
        for i in range(len(test_row)): #test_row have 4 coulumn
             distance += (test_row[i] - train_row[i])**2
        return np.sqrt(distance)
    
    #sort_distances function sorts the distances and returns the sorted array.
    def sort_distances(self, test_row):
        distances = [] #an array for the distances 
        
        for i in range(len(self.x_train)): #x_train has 105 rows
            distances.append((self.y_train[i], self.euclidean(test_row, self.x_train[i])))    

        distances.sort(key=lambda distances: distances[1]) #Sorted according to the distance
        return distances
    
    #The count function takes whatever value is more in the neighbors and returns it.
    def count(self, neighbors): 
        counts=[] #an array for the count
        for i in range(len(neighbors)):
            counts.append([neighbors[i], neighbors.count(neighbors[i])])
            #Neighbors and the count value of neighbors is append to the counts array.
        most = 0
        pred=0  
        for i in range(len(counts)): 
            if(most < counts[i][1]): #The most count value is returned.
                most = counts[i][1]
                pred = counts[i][0]
        return pred  
    


In [13]:
#first of all, implement the KNN algorithm using the sklearn library.
#for the k = 1, k=3, k=5 Euclidean 
for k in [1,3,5]:
    knn = KNeighborsClassifier(n_neighbors=k,         #Number of neighbors
                               weights = "uniform",   #All points in each neighborhood are weighted equally.
                               #algorithm="brute",    
                               metric= "euclidean")   #the distance metric
    knn.fit(x_train,y_train)
    y_pred = knn.predict(x_test)
    print("\nK: %d \nScore: %.3f" %(k,accuracy_score( y_test, y_pred)))  #accuracy score
    print("Confusion Matrix:\n",confusion_matrix( y_test, y_pred))       #confusion matrix


K: 1 
Score: 0.978
Confusion Matrix:
 [[16  0  0]
 [ 0 17  1]
 [ 0  0 11]]

K: 3 
Score: 0.978
Confusion Matrix:
 [[16  0  0]
 [ 0 17  1]
 [ 0  0 11]]

K: 5 
Score: 0.978
Confusion Matrix:
 [[16  0  0]
 [ 0 17  1]
 [ 0  0 11]]


In [14]:
for k in [1,3,35]:
    knn = KNN(x_train,y_train,k)
    y_pred = knn.predict(x_test)
    print("\nK: %d \nScore: %.3f" %(k,accuracy_score( y_test, y_pred)))  #accuracy score
    print("Confusion Matrix:\n",confusion_matrix( y_test, y_pred))       #confusion matrix


K: 1 
Score: 0.978
Confusion Matrix:
 [[16  0  0]
 [ 0 17  1]
 [ 0  0 11]]

K: 3 
Score: 0.978
Confusion Matrix:
 [[16  0  0]
 [ 0 17  1]
 [ 0  0 11]]

K: 35 
Score: 0.933
Confusion Matrix:
 [[16  0  0]
 [ 0 15  3]
 [ 0  0 11]]


In [15]:
#In this section, the KNN algorithm is implemented for a random value of k.
random_k = random.randint(1,105)      #An arbitrary value of k between 1 and 105
print("Random K value: ", random_k)
knn = KNN(x_train, y_train, random_k)
y_pred = knn.predict(x_test)
print("\nK: %d \nScore: %.3f" %(random_k,accuracy_score( y_test, y_pred)))  #accuracy score       
print("Confusion Matrix:\n",confusion_matrix( y_test, y_pred))              #confusion matrix

Random K value:  63

K: 63 
Score: 0.867
Confusion Matrix:
 [[16  0  0]
 [ 0 12  6]
 [ 0  0 11]]


In [16]:
k_value = int(input("Enter K value: "))   
knn = KNN(x_train, y_train, k_value)
y_pred = knn.predict(x_test)
print("\nK: %d \nScore: %.3f" %(k_value,accuracy_score( y_test, y_pred)))  #accuracy score       
print("Confusion Matrix:\n",confusion_matrix( y_test, y_pred))              #confusion matrix

Enter K value: 5

K: 5 
Score: 0.978
Confusion Matrix:
 [[16  0  0]
 [ 0 17  1]
 [ 0  0 11]]
